### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by vdesabou** [shawnrice/alphred#3]
Hi Shawn,

I'm still trying to use Alphred, but I'm running into issues:

1/ I often rename workflow directories, so instead of user.workflow.xxx I use different name, but this part of the code prevents this:

```
if [[ ! $(basename "${PWD}") =~ 'user.workflow.' ]]; then
    $temp=$(basename "${PWD}")
    echo "You  cfcf can execute this script only from an Alfred Workflow $temp"
    exit 1
fi
```

Also, I often create symbolic links for my workflows, it seems that even if I rename my directory to start with user.workflow, basenane does not take into account symbolic links.

2/ When I execute Alfred, I get 'server.sh: line 62: Alphred::extend_query_server: command not found'. So as I understand it, I need to define a function ``Alphred::extend_query_server` when query length is < 3. Why exactly? I want to call my workflow even if query length is 0. I'm not sure to get why we need to do this.

3/ After adding the missing function, I get `curl: option --data query=&: is unknown`error

BTW, I have setup my workflow like this:

![pic](https://cloud.githubusercontent.com/assets/4061923/6244577/7cf22bfe-b755-11e4-917f-0b60e214c4fb.png)

**Comment by shawnrice** [comment]
This is good. I haven't looked at this part of the library in a couple of months, and so these are precisely the things that I need to think about. The idea behind it was to have a reusable server, just in case you happened to launch the server from two different workflows, there wouldn't be a clash. The workflow directory renaming and symlinking poses a problem to the current implementation, and so I'll have to experiment to see if I can find a way around it. 

Min query should be set to 0 rather than 3 by default (and probably set somewhere else like `workflow.ini`).

I think I understand the cURL error there. Definitely a bug.

**Comment by shawnrice** [comment]
Okay, I think that https://github.com/shawnrice/alphred/commit/23286272cdc47287d53160a2915405106d7b52d0 should fix the problems above (except for setting min query, which is now at 0 by default).

Let me know if it works out for you this time. Just do the update:

``` shell
php Alphred.phar update-self-master
php Alphred.phar create-server-scripts
```

And let me know if it works this time.

**Comment by vdesabou** [comment]
Hi Shawn,

Just a remark, I think you should mention in the doc that `alphred_urlencode.sed`must be copied as well..

Otherwise we get:

```
[STDERR: alfred.workflow.input.scriptfilter] sed: /Users/vdesabou/Dropbox/github/alfred-spotify-mini-player/spotify-mini-player/src/alphred_urlencode.sed: No such file or directory
```

I have this error now:

```
curl -fsS --request POST http://localhost:8972/spotify-mini-player/./src/main.php --data 'alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.vdesabou.spotify.mini.player&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.vdesabou.spotify.mini.player&alfred_workflow_data=/Users/vdesabou/Library/Application Support/Alfred 2/Workflow Data/com.vdesabou.spotify.mini.player&alfred_workflow_name=Spotify Mini Player&alfred_workflow_uid=user.workflow.spotify-mini-player'

curl: (22) The requested URL returned error: 404 Not Found
```

The process is started and listening on the port:

```
501  7653     1   0 11:26AM ??         0:00.10 php -S localhost:8972 -t /Users/vdesabou/Dropbox/github/alfred-spotify-mini-player/spotify-mini-player/src/../

netstat -an | grep 8972
tcp6       0      0  ::1.8972               *.*                    LISTEN
```

I've set workflow with:

```
bash ./src/server.sh "./src/main.php" "{query}"
```

I set the source files in `src`directory like this:

```
MacBookPro-Vincent:[11:30:10]/Users/vdesabou/Dropbox/Alfred.alfredpreferences/workflows/alfred-spotify-mini-player/src>
ll
total 1680
-rw-r--r--@  1 vdesabou  staff    6148 Dec 31 12:51 .DS_Store
-rwxr-xr-x@  1 vdesabou  staff     619 Jan 23 08:49 track_info.ksh
-rwxr-xr-x@  1 vdesabou  staff    2868 Jan 23 08:49 spotify_mini_player_notifications.ksh
-rw-r--r--@  1 vdesabou  staff    5467 Jan 23 08:49 country_names.json
-rwxr-xr-x@  1 vdesabou  staff   17489 Jan 29 10:29 workflows.php
-rw-r--r--@  1 vdesabou  staff    9042 Feb  2 10:53 debug.php
-rw-r--r--@  1 vdesabou  staff  285056 Feb 19 09:57 menu.php
-rw-r--r--@  1 vdesabou  staff   45411 Feb 19 17:11 action.php
-rw-r--r--@  1 vdesabou  staff  231491 Feb 20 10:09 Alphred.phar
-rw-r--r--@  1 vdesabou  staff    1779 Feb 20 10:10 server.php
-rw-r--r--@  1 vdesabou  staff    1050 Feb 20 10:10 kill.sh
-rw-r--r--@  1 vdesabou  staff     346 Feb 20 10:10 alphred_urlencode.sed
-rw-r--r--@  1 vdesabou  staff  192081 Feb 20 10:16 functions.php
drwxr-xr-x@ 86 vdesabou  staff    2924 Feb 20 10:17 ..
-rw-r--r--@  1 vdesabou  staff   17610 Feb 20 10:29 main.php
-rw-r--r--@  1 vdesabou  staff    4671 Feb 20 11:14 server.sh
drwxr-xr-x@ 17 vdesabou  staff     578 Feb 20 11:14 .
```

Any idea what's going on?

**Comment by shawnrice** [comment]
I'll look again in a minute, but it might be that you're running one version behind (there were two quick updates). Try updating to master again, deleting the server scripts and recreating them.

If that still doesn't work, can you try installing the workflow that is in the example directory of this repo and seeing if that works?

**Comment by vdesabou** [comment]
> I'll look again in a minute, but it might be that you're running one version behind (there were two quick updates). Try updating to master again, deleting the server scripts and recreating them.

I think I had latest version when I tested it

> If that still doesn't work, can you try installing the workflow that is in the example directory of this repo and seeing if that works?

So I tried, but the only thing I get is:

```
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?> <items> <item/> </items>
```

I have been asked for my github account username first, and then got only this..I have not been asked for my password.

**Comment by shawnrice** [comment]
Well, the output on the example workflow means that the server scripts are working on your computer, but other things are going wrong.

Can you run this script from the command line:

``` php
require_once( 'Alphred.php' );
$a = new Alphred;
$password = $a->get_password_dialog('This is some text', 'This is a title');
print $password;
```

and let me know if that goes through? It should create a hidden input box. And then spit back out whatever you wrote.

You're right on updating the docs for `alphred_urlencode.sed`; that file is new as of 0.9.2.

For the cli-server, can you try moving all the server files into the root of the workflow and let me know if that helps? Then, try:

``` shell
bash server.sh src/main.php "{query}"
```

without the `.` to see if that makes any difference (trying to find the bugs).

Do you have phpunit installed on your computer? If so, would you mind cloning the repo and, from the root, running `./test_runner.sh`? If you don't have Chrome and iTerm some of the tests will fail, but that might give me some more knowledge about what's going wrong.

Lastly, can you email me what you've done on the workflow with Alphred integration? I'd love to see if I can push it to make it work. That'll help me debug.

**Comment by shawnrice** [comment]
I changed the way the scripts work so that it launches the server in `$alfred_preferences/workflows`, which should be stable and re-usable. It also should work with symlinks; **however**, right now the symlink directory needs to match the name of the actual directory (i.e. `example -> example`, not `example -> alphred_example`). The reason for the name match is that `pwd`, `$PWD`, `pwd -L` all seem to resolve to the real path when launched inside Alfred in a symlinked workflow. I need to get the dirname in order to construct the URL (`http://localhost:8792/${directory}/{this_is_the_script}`).

I'll keep looking for a way to find the symlinked directory name.

The server scripts can also now live in a sub-directory, as long as they're all in the same directory.

**Comment by shawnrice** [comment]
I fixed the example workflow. I had some dumb old code mixing syntax from using the components and using the wrapper.

Also, the xml from the cli-server now pretty prints the XML, which should be good. Also, to note, the console log does not work with the cli-server. There is no way around this as the console log writes to STDERR, and, when using nohup to launch the php server (necessary to make sure the workflows don't hang because I have to detach all the pipes).

I still haven't figured out the symlink problem. I thought that, if `$alfred_preferences` didn't manage to `grep` `pwd`, then I could `grep` the output of `ls -l "${alfred_preferences}/workflows"`, but I don't get the full paths to match `pwd`. For me, it looks like:

```
lrwxr-xr-x   1 Sven  staff    46 Feb 18 20:01 example -> /Users/Sven/Documents/Alfred2/alphred/example/
```

(Yes, for some strange reason, my username is Sven, which has no relation to anything about me other than the username).

But, grepping `example` would also match `examples`, meaning false positives.

**Comment by shawnrice** [comment]
Okay, so, I did something that should make sure that the cli-server still works even if the symlinked directory doesn't share the same name. Which is, basically, what is above, but with some better regexes.

Update to master:

``` shell
php Alphred.phar update-self-master
```

Rebuild the server scripts, and then let's see if it works.

Thanks for helping me find these bugs. The cli-server scripts are pretty unorthodox.

**Comment by vdesabou** [comment]
Hi Shawn,

Thanks for this!
So I had done another retries with latest version.

For example workflow, I got the window where password was asked, and then when I invoke the workflow, I get:

```
Starting debug for 'Github Repos'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: -:1: parser error : Extra content at the end of the document
<br /> <b>Warning</b>: Invalid argument supplied for foreach() in <b>/Users/vdes
       ^
```

If I put more debug traces, I get:

```
Starting debug for 'Github Repos'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: + cmd='curl -fsS --request POST '\''http://localhost:8972/user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623/script-filter.php'\'' --data '\''alfred_preferences=/Users/vdesabou/Dropbox/Alfred.alfredpreferences&alfred_preferences_localhash=c9ff60060ca8483123c8085f320a643a6e9dca88&alfred_theme=alfred.theme.custom.C8537E29-6A5B-4613-AEDD-7754D7CE8817&alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.spr.gh.repos&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.spr.gh.repos&alfred_workflow_data=/Users/vdesabou/Library/Application Support/Alfred 2/Workflow Data/com.spr.gh.repos&alfred_workflow_name=Github Repos&alfred_workflow_uid=user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623'\'''
+ xmllint --format -
++ eval curl -fsS --request POST ''\''http://localhost:8972/user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623/script-filter.php'\''' --data ''\''alfred_preferences=/Users/vdesabou/Dropbox/Alfred.alfredpreferences&alfred_preferences_localhash=c9ff60060ca8483123c8085f320a643a6e9dca88&alfred_theme=alfred.theme.custom.C8537E29-6A5B-4613-AEDD-7754D7CE8817&alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.spr.gh.repos&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow' 'Data/com.spr.gh.repos&alfred_workflow_data=/Users/vdesabou/Library/Application' Support/Alfred 2/Workflow 'Data/com.spr.gh.repos&alfred_workflow_name=Github' 'Repos&alfred_workflow_uid=user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623'\'''
+++ curl -fsS --request POST http://localhost:8972/user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623/script-filter.php --data 'alfred_preferences=/Users/vdesabou/Dropbox/Alfred.alfredpreferences&alfred_preferences_localhash=c9ff60060ca8483123c8085f320a643a6e9dca88&alfred_theme=alfred.theme.custom.C8537E29-6A5B-4613-AEDD-7754D7CE8817&alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.spr.gh.repos&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.spr.gh.repos&alfred_workflow_data=/Users/vdesabou/Library/Application Support/Alfred 2/Workflow Data/com.spr.gh.repos&alfred_workflow_name=Github Repos&alfred_workflow_uid=user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623'
+ echo '<br' '/>' '<b>Warning</b>:' Invalid argument supplied for 'foreach()' in '<b>/Users/vdesabou/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.DCC20847-C27D-4250-9781-F80FDFA44623/script-filter.php</b>' on line '<b>115</b><br' '/>' '<?xml' 'version="1.0"' 'encoding="UTF-8"?>' '<items>' '<item' 'autocomplete=""' 'valid="no">' '<title>Error:' No results 'found.</title>' '<icon>/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Unsupported.icns</icon>' '<subtitle>Please' try a different 'query.</subtitle>' '</item>' '</items>'
-:1: parser error : Extra content at the end of the document
<br /> <b>Warning</b>: Invalid argument supplied for foreach() in <b>/Users/vdes
       ^
```

I also tried with my Spotify Mini Player workflow, I get:

```
Starting debug for 'Spotify Mini Player'

[ERROR: alfred.workflow.input.scriptfilter] Code 1: curl: (22) The requested URL returned error: 404 Not Found
-:2: parser error : Start tag expected, '<' not found

^
```

If I set `set -x` I get:-

```
[ERROR: alfred.workflow.input.scriptfilter] Code 1: + cmd='curl -fsS --request POST '\''http://localhost:8972/lrwxr%2dxr%2dx%201%20vdesabou%20staff%2077%20Feb%2020%2011%3a28%20alfred%2dspotify%2dmini%2dplayer%20%2d>%20%2fUsers%2fvdesabou%2fDropbox%2fgithub%2falfred%2dspotify%2dmini%2dplayer%2fspotify%2dmini%2dplayer/src/main.php'\'' --data '\''alfred_preferences=/Users/vdesabou/Dropbox/Alfred.alfredpreferences&alfred_preferences_localhash=c9ff60060ca8483123c8085f320a643a6e9dca88&alfred_theme=alfred.theme.custom.C8537E29-6A5B-4613-AEDD-7754D7CE8817&alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.vdesabou.spotify.mini.player&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.vdesabou.spotify.mini.player&alfred_workflow_data=/Users/vdesabou/Library/Application Support/Alfred 2/Workflow Data/com.vdesabou.spotify.mini.player&alfred_workflow_name=Spotify Mini Player&alfred_workflow_uid=alfred-spotify-mini-player'\'''
+ xmllint --format -
++ eval curl -fsS --request POST ''\''http://localhost:8972/lrwxr%2dxr%2dx%201%20vdesabou%20staff%2077%20Feb%2020%2011%3a28%20alfred%2dspotify%2dmini%2dplayer%20%2d>%20%2fUsers%2fvdesabou%2fDropbox%2fgithub%2falfred%2dspotify%2dmini%2dplayer%2fspotify%2dmini%2dplayer/src/main.php'\''' --data ''\''alfred_preferences=/Users/vdesabou/Dropbox/Alfred.alfredpreferences&alfred_preferences_localhash=c9ff60060ca8483123c8085f320a643a6e9dca88&alfred_theme=alfred.theme.custom.C8537E29-6A5B-4613-AEDD-7754D7CE8817&alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.vdesabou.spotify.mini.player&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow' 'Data/com.vdesabou.spotify.mini.player&alfred_workflow_data=/Users/vdesabou/Library/Application' Support/Alfred 2/Workflow 'Data/com.vdesabou.spotify.mini.player&alfred_workflow_name=Spotify' Mini 'Player&alfred_workflow_uid=alfred-spotify-mini-player'\'''
+++ curl -fsS --request POST 'http://localhost:8972/lrwxr%2dxr%2dx%201%20vdesabou%20staff%2077%20Feb%2020%2011%3a28%20alfred%2dspotify%2dmini%2dplayer%20%2d>%20%2fUsers%2fvdesabou%2fDropbox%2fgithub%2falfred%2dspotify%2dmini%2dplayer%2fspotify%2dmini%2dplayer/src/main.php' --data 'alfred_preferences=/Users/vdesabou/Dropbox/Alfred.alfredpreferences&alfred_preferences_localhash=c9ff60060ca8483123c8085f320a643a6e9dca88&alfred_theme=alfred.theme.custom.C8537E29-6A5B-4613-AEDD-7754D7CE8817&alfred_theme_background=rgba(255,255,255,1.00)&alfred_theme_subtext=0&alfred_version=2.6&alfred_version_build=374&alfred_workflow_bundleid=com.vdesabou.spotify.mini.player&alfred_workflow_cache=/Users/vdesabou/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.vdesabou.spotify.mini.player&alfred_workflow_data=/Users/vdesabou/Library/Application Support/Alfred 2/Workflow Data/com.vdesabou.spotify.mini.player&alfred_workflow_name=Spotify Mini Player&alfred_workflow_uid=alfred-spotify-mini-player'
curl: (22) The requested URL returned error: 404 Not Found
+ echo
-:2: parser error : Start tag expected, '<' not found

^
```

The server process is:

```
  501  3152     1   0 12:53PM ??         0:00.09 php -S localhost:8972 -t /Users/vdesabou/Dropbox/Alfred.alfredpreferences/workflows
```

EDIT: My symbolic link is:

```
MacBookPro-Vincent:[12:57:41]/Users/vdesabou/Dropbox/Alfred.alfredpreferences/workflows>
ll alfred-spotify-mini-player
lrwxr-xr-x  1 vdesabou  staff  77 Feb 20 11:28 alfred-spotify-mini-player -> /Users/vdesabou/Dropbox/github/alfred-spotify-mini-player/spotify-mini-player
```

**Comment by shawnrice** [comment]
So, the example workflow is failing because it didn't get anything usable from Github, and I didn't include error checking for an empty repository. Can you verify that the password is stored correctly in the keychain? Just open up Keychain Access and search for `com.spr.gh.repos`. If it is correct, then can you open up the cache directory `~/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.spr.gh.repos/`. Verify that there is a folder in there called `api.github.com`, and check to see if the files have any contents in them (if they're there). They should just be raw JSON data from Github.

For that error with the spotify mini player, the sed regex isn't working right. Something slipped through. The line:

``` shell
directory=$(echo $dir | grep "$(pwd)" | sed 's|^[lrwx@-]\{1,\}[ ]*[0-9]\{1,\}[ ]*[^ ]\{1,\}[ ]*[a-zA-Z]\{1,\}[ ]*[0-9]\{1,\}[ ]*[A-Za-z]\{1,\}[ ]*[0-9]\{1,\}[ ]*[0-9]\{2\}:[0-9]\{2\}\([A-Za-z0-9 -]\{1,\}\) \-\> '"$PWD"\/'|\1|g' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
```

from `server.sh` is supposed to filter out everything except the name of the directory. I'll rework that to see where it is failing.

**Comment by shawnrice** [comment]
The regex problem should be fixed as of the last commit (2f8b5a1). There was an optional trailing slash that the regex thought was not optional.

**Comment by vdesabou** [comment]
> So, the example workflow is failing because it didn't get anything usable from Github

I got it working. I've two factor authentication in place so I changes password with application password.
Now the Example workflow is working fine!

**Comment by shawnrice** [comment]
I think that we've gotten everything worked out on this one, so I'm closing.

The bugs in the scripts should be fixed. It also stands up to symlinked workflows, routing appropriately.

For others who read this thread, cURL errors with 22 usually mean that the script itself also is buggy. A 500 error means that the PHP server couldn't render the script. The cli-server doesn't do error reporting in the same way, so it's best to debug the script itself without the cli-server. Also, don't include files like `require_once( './src/main.php' );` because `.` is different when you use the cli-server (this is necessary in order to make sure that workflows don't monopolize the server). Instead, use relative paths like `require_once( __DIR__ . '/src/main.php' );`, remembering that `__DIR__` is the directory in which the current php file is. So, a file already in `src` would include `main.php` like `require_once( __DIR__ . '/main.php' );`.
